# Generated by Django 6.1.1 on 2026-09-06 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PERSONA', 'Persona Natural'), ('EMPRESA', 'Persona Juridica')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Flujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('velocidad', models.PositiveBigIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('JIRON', 'Jiron'), ('AVENIDA', 'Avenida'), ('CALLE', 'Calle'), ('PASAJE', 'Pasaje')], max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('distrito', models.CharField(max_length=100)),
                ('urbanizacion', models.CharField(blank=True, max_length=100)),
                ('manzana', models.CharField(blank=True, max_length=10)),
                ('lote', models.CharField(blank=True, max_length=10)),
                ('referencia', models.CharField(blank=True, max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='FlujoPaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('flujo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.flujo')),
                ('paso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.paso')),
            ],
        ),
        migrations.AddField(
            model_name='flujo',
            name='pasos',
            field=models.ManyToManyField(through='api.FlujoPaso', to='api.paso'),
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carne de Extranjeria')], max_length=20)),
                ('numero_documento', models.CharField(max_length=9)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('distrito_nacimiento', models.CharField(max_length=100)),
                ('padre', models.CharField(max_length=100)),
                ('madre', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=9)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11)),
                ('razon_social', models.CharField(max_length=100)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('representante_legal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.persona')),
            ],
        ),
        migrations.CreateModel(
            name='PromocionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.promocion')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('INSTALADO', 'Instalado'), ('ANULADO', 'Anulado')], default='EN_PROCESO', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.cliente')),
                ('flujo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.flujo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.producto')),
                ('promociones', models.ManyToManyField(through='api.PromocionVenta', to='api.promocion')),
            ],
        ),
        migrations.AddField(
            model_name='promocionventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.venta'),
        ),
        migrations.CreateModel(
            name='VentaPaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('OBSERVADO', 'Observado'), ('SUBSANANDO', 'Subsanando'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('flujo_paso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.flujopaso')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.venta')),
            ],
        ),
        migrations.AddConstraint(
            model_name='flujopaso',
            constraint=models.UniqueConstraint(fields=('flujo', 'paso'), name='unique_flujo_paso'),
        ),
        migrations.AddConstraint(
            model_name='flujopaso',
            constraint=models.UniqueConstraint(fields=('flujo', 'orden'), name='unique_flujo_orden'),
        ),
        migrations.AddConstraint(
            model_name='promocionventa',
            constraint=models.UniqueConstraint(fields=('venta', 'promocion'), name='unique_venta_promocion'),
        ),
    ]
