# Generated by Django 6.1.1 on 2026-09-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_user_perm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='distrito_nacimiento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='madre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='padre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
