# Generated by Django 6.1.1 on 2026-09-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_persona_datos_nacimiento_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujo',
            name='tipo_cliente',
            field=models.CharField(choices=[('PERSONA', 'Persona Natural'), ('EMPRESA', 'Persona Juridica')], max_length=20),
        ),
    ]
