# Generated by Django 6.1.1 on 2026-09-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_duplicate_direcciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='interior',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
