# Generated by Django 6.1.1 on 2026-09-21 01:09

import django.db.models.deletion
from django.apps import apps as django_apps
from django.conf import settings
from django.contrib.auth.management import create_permissions
from django.db import migrations, models


def grant_plantilla_contrato(apps, schema_editor):
    create_permissions(django_apps.get_app_config("api"), verbosity=0)
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    content_type, _created = ContentType.objects.get_or_create(
        app_label="api", model="plantillacontrato"
    )
    permisos = list(
        Permission.objects.filter(
            content_type=content_type,
            codename__in=[
                "view_plantillacontrato",
                "add_plantillacontrato",
                "change_plantillacontrato",
                "delete_plantillacontrato",
            ],
        )
    )
    try:
        admin = Group.objects.get(name="Administrador")
    except Group.DoesNotExist:
        return
    admin.permissions.add(*permisos)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_generar_contrato"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantillaContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=40, unique=True)),
                ("nombre_archivo", models.CharField(max_length=200)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("tamano", models.PositiveIntegerField(default=0)),
                ("contenido", models.BinaryField()),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plantillas_contrato",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(grant_plantilla_contrato, migrations.RunPython.noop),
    ]
